version: "3"

# GETTING STARTED
# 0. Install Docker for Mac: https://download.docker.com/mac/stable/Docker.dmg
# 1. Update host file. Remove any conflicting entries. Add the following entries:
#       127.0.0.1     <EDIT THIS>
# 2. Export the prod db OR get the latest automated backup
#       - sh bin/sql-backup.sh
#       - sh bin/get-latest-backup.sh
# 3. Start docker containers
#       docker-compose up -d
# 4. Import the db. See the USEFUL COMMANDS #1 below.

# USEFUL COMMANDS
# 1. Import a db from the ./backups directory (update sql filename)
#       docker-compose exec mysql sh -c 'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" < /app/backups/backup-20180103-110410.sql'

# COMMON COMMANDS
# 1. Starting docker containers
#       docker-compose start
# 2. Stopping docker containers
#       docker-compose stop

services:
    web:
        image: flipbox/php:71-amazonlinux-apache
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/html
            - ./vendor/flipboxfactory/evo/httpd.d/web/main.conf:/etc/httpd/conf.d/welcome.conf
            - ./vendor/flipboxfactory/evo/httpd.d/web/perf.conf:/etc/httpd/conf.d/01-perf.conf
        environment:
            ENVIRONMENT: LOCAL
            DB_SERVER: db
            DB_USER: craft
            DB_PASSWORD: craft
            DB_DATABASE: craft
            
    db:
        image: mysql:5.6
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: craft
            MYSQL_USER: craft
            MYSQL_PASSWORD: craft
        volumes:
            - .:/app
