#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * NOTICE: APP_ROOT is from the vendor package directory.
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('APP_ROOT') or define('APP_ROOT', dirname(__DIR__, 4));
defined('EVO_ROOT') or define('EVO_ROOT', dirname(__DIR__));

// register Composer autoloader
require dirname(__DIR__, 4) . '/vendor/autoload.php';

// include Yii class file
require dirname(__DIR__, 4) . '/vendor/yiisoft/yii2/Yii.php';

// load application configuration
$config = require dirname(__DIR__) . '/src/config/console.php';

// Move Yii's autoloader to the end (Composer's is faster when optimized)
spl_autoload_unregister(['Yii', 'autoload']);
spl_autoload_register(['Yii', 'autoload'], true, false);

$application = new \flipboxlabs\evo\Evo($config);
$exitCode = $application->run();
exit($exitCode);
